// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mafwdddrlbbvjvyinhdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZndkZGRybGJidmp2eWluaGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTgxMTMsImV4cCI6MjA3MjQ5NDExM30.JHr-ENqHN81tcTRbx6sp56pHDq9nMGq8-WgrO7kkBbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});